name: lint schema

on:
  pull_request:
    paths:
      - .schema/*

jobs:
  lint-schema:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm install -g ajv-cli
        name: install ajv-cli
      - run: ajv --spec draft7 compile -s .schema/vrsn.json
        name: validate schema
      - run: |
          curl -Ls "https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz" | \
            gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo
        name: install taplo
      - run: taplo --verbose lint .schema/vrsn.toml
        name: validate example config file
